plugins {
    id 'java'
    id 'maven-publish'
}

repositories {
    mavenLocal()
    maven {
        url = uri('https://repo.maven.apache.org/maven2/')
    }
    mavenCentral()
}

group = 'com.pb.validation'
version = '0.0.1-SNAPSHOT'
description = 'simple-validation-framework'

java.sourceCompatibility = JavaVersion.VERSION_25

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:6.1.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:6.1.2'

    testImplementation 'org.assertj:assertj-core:3.27.7'
}

publishing {
    publications {
        maven(MavenPublication) {
            from(components.java)
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
}
